Import('env')
if env['PLATF'] == 'kachel':
    env = env.Clone()
    env.Append(
        CXXFLAGS = ' -fno-exceptions',
        LINKFLAGS = ' -fno-exceptions',
    )
    env.M3Program(
        env,
        'standalone',
        env.Glob('*.cc'),
        NoSup = True,
        libs = ["c", "heap", "base", "supc++"]
    )
