Import('env')
if env['ARCH'] == 'gem5':
    env = env.Clone()
    env["CXXFLAGS"] = env["CXXFLAGS"].replace('-flto','')
    env.M3Program(env, 'standalone', env.Glob('*.cc'), NoSup = True, libs = ["c"])
