Import('env')
if env['PLATF'] == 'kachel':
    env = env.Clone()
    env.Append(
        CXXFLAGS = ' -fno-exceptions',
        LINKFLAGS = ' -fno-exceptions',
    )
    env.M3Program(
        env,
        'standalone',
        env.Glob('*.cc'),
        NoSup = True,
        libs = ["c", "heap", "base", "supc++"]
    )

    for s in ["sender", "receiver"]:
        env.M3Program(
            env,
            "standalone-" + s,
            [env.Glob("env.cc"), env.Glob(s + '/*.cc')],
            NoSup = True,
            libs = ["c", "heap", "base", "supc++"]
        )
