Import('env')

myenv = env.Clone()

myenv.Append(
    CPPPATH = '.',
    CXXFLAGS = ' -fno-exceptions',
    LINKFLAGS = ' -fno-exceptions',
)

sources = [
    myenv.Glob('*.cc'),
    myenv.Glob('*/*.cc'),
    myenv.Glob('arch/$ARCH/*.cc'),
    myenv.Glob('arch/$ARCH/*/*.cc')
]
if env['ARCH'] != 'host':
    sources += [env.Glob('arch/baremetal/*.cc')]
    myenv.Append(LINKFLAGS = ' -Wl,--whole-archive -lisr -Wl,--no-whole-archive')

myenv.M3Program(
    myenv,
    target = 'kernel',
    source = sources,
    libs = ['X11', 'rt'] if myenv['ARCH'] == 'host' else ['isr']
)
