Import('env')

myenv = env.Clone()

myenv.Append(
    CPPPATH = '.',
    CXXFLAGS = ' -fno-exceptions',
    LINKFLAGS = ' -fno-exceptions',
)

sources = [
    myenv.Glob('*.cc'),
    myenv.Glob('*/*.cc'),
    myenv.Glob('arch/$ARCH/*.cc'),
    myenv.Glob('arch/$ARCH/*/*.cc')
]
if env['ARCH'] != 'host':
    # we need muldefs here, because libpaging.a and libgcc/libgcc_eh contain _Unwind_Resume
    myenv.Append(LINKFLAGS = ' -Wl,-z,muldefs -Wl,--whole-archive -lisr -Wl,--no-whole-archive')

myenv.M3Program(
    myenv,
    target = 'kernel',
    source = sources,
    libs = [] if myenv['ARCH'] == 'host' else ['isr', 'paging'],
)
