Import('env')

if env['TGT'] != 'host':
    for f in [env.Glob('$ISA/*.S')]:
        obj = env.Object(source = f)
        env.Install(env['LIBDIR'], obj)
    for f in env.Glob('$SYSGCCLIBPATH/crt*'):
        env.Install(env['LIBDIR'], f)
