Import('env')

if env['ARCH'] != 'host':
    for f in [env.Glob('$ARCH/*.S'), env.Glob('$ARCH-$ISA/*.S')]:
        obj = env.Object(source = f)
        env.Install(env['LIBDIR'], obj)
    for f in env.Glob('$SYSGCCLIBPATH/crt*'):
        env.Install(env['LIBDIR'], f)
