Import('env')
if not ARGUMENTS.get('build_fs', 0):
    env.InstallFiles('$FSDIR/default', '.', scan=1, exclude=['SConscript'])

if env['ARCH'] == 'host':
    blocks = 160 * 1024
else:
    blocks = 16 * 1024
env.BuildFSImage(target = 'default.img', source = '$FSDIR/default', blocks = blocks, inodes = 512)
