Import('env')

if env['TGT'] == 'gem5':
    myenv = env.Clone()
    myenv.Append(
        LINKFLAGS = ' -nostartfiles',
    )
    if myenv['ISA'] == 'x86_64':
        myenv['TRIPLE'] = 'x86_64-unknown-gem5-pemux-gnu'

    entry = myenv.Object(myenv.Glob('src/arch/$ISA/Entry.S'))
    myenv.RustProgram(
        myenv,
        target = 'pemux',
        libs = ['isr'],
        startup = entry,
        varAddr = False,
    )
