Import('env')

env = env.Clone()
env.Append(
    CXXFLAGS = ' -fno-exceptions -fno-rtti',
    LINKFLAGS = ' -fno-exceptions -fno-rtti',
)

sources = [
    env.Glob('*.cc'), env.Glob('*/*.cc'),
    env.Glob('isa/$ISA/*.S'), env.Glob('isa/$ISA/*.cc')
]

lib = env.StaticLibrary(
    target = 'thread',
    source = sources
)
env.Install(env['LIBDIR'], lib)
