Import('env')
if env['ARCH'] == 'gem5':
    lib = env.StaticLibrary(target = 'm', source = env.Glob('*.cc'))
    env.Install(env['LIBDIR'], lib)

    lib = env.StaticLibrary(target = 'stdc++', source = env.Glob('*.cc'))
    env.Install(env['LIBDIR'], lib)
