Import('env')
if env['TGT'] == 'host':
    myenv = env.Clone()
    myenv.Append(CXXFLAGS = ' -fno-exceptions')
    myenv['CXXFLAGS'] = str(myenv['CXXFLAGS']).replace('-flto', '')
    lib = myenv.StaticLibrary(
        target = 'libhost',
        source = myenv.Glob('init.cc'),
    )
    myenv.Install(myenv['LIBDIR'], lib)
