[package]
name = "raser"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/raser.rs"
crate-type = ["staticlib"]

[dependencies]
m3 = { path = "../../libs/rust/m3" }
rot = { path = "../../libs/crypto/rot" }
