import os

Import('env')

sources = [
    env.Glob('*.cc'), env.Glob('*/*.cc'),
    env.Glob('arch/$TGT/*.cc')
]

lib = env.StaticLibrary(
    target = 'libm3',
    source = sources
)
env.Install(env['LIBDIR'], lib)
