Import('hostenv')

henv = hostenv.Clone()
if hostenv['BUILD'] == 'release':
    henv.Append(CRGFLAGS = ' --release')

prog = henv.Command(
    'gem5log', [henv.Glob('src/*.rs'), 'Cargo.toml'],
    Action(
        'cd ${SOURCE.dir.dir}'
        + ' && cargo build -q $CRGFLAGS -Z unstable-options --out-dir ${TARGET.abspath}.out'
        + ' && cp -f ${TARGET.abspath}.out/gem5log ${TARGET.abspath}.out/..',
        '$CRGCOMSTR'
    )
)
henv.Install(henv['TOOLDIR'], prog)
