Import('hostenv')

if hostenv['HAS_OTF']:
    traceenv = hostenv.Clone()
    traceenv.ParseConfig('tud-otfconfig --includes --libs')
    traceenv.Program(
        target = 'gem52otf',
        source = traceenv.Glob('*.cc'),
    )
else:
    print('Cannot execute tud-otfconfig, skipping gem52otf...')
