Import('env')

if env['TGT'] != 'host':
    myenv = env.Clone()
    myenv.Append(CXXFLAGS = ' -fno-exceptions')
    # disable lto for gem5 for now, since it doesn't workhere ("plugin needed to handle lto object")
    # I don't know why it works for libm3, but not for libc.
    myenv['CXXFLAGS'] = str(myenv['CXXFLAGS']).replace('-flto', '')
    lib = myenv.StaticLibrary(
        target = 'libc',
        source = [
            myenv.Glob('*/*.cc'),
            myenv.Glob('arch/$ISA/*.S'),
        ]
    )
    myenv.Install(myenv['LIBDIR'], lib)
