Import('env')
env.InstallFiles('$FSDIR/bench', '.', scan=1)

if env['ARCH'] == 'host':
    blocks = 160 * 1024
else:
    blocks = 64 * 1024
env.BuildFSImage(target = 'bench.img', source = '$FSDIR/bench', blocks = blocks, inodes = 4096)
