Import('env')
env.InstallFiles('$FSDIR/bench', '.', scan=1)

if env['ARCH'] == 'host':
    blocks = 160 * 1024
else:
    blocks = 64 * 1024
env.BuildFSImage(target = 'bench.img', source = '$FSDIR/bench', blocks = blocks, inodes = 4096)

if env['ARCH'] == 't2' or env['ARCH'] == 't3':
    args = '--sim' if env['ARCH'] == 't3' else ''
    env.M3FileDump(target = 'bench.img.mem', source = 'bench.img', addr = 0x1000000, args = args)
