Import('env')

if env['ARCH'] == 'gem5':
    myenv = env.Clone()

    # -O0 makes the code too large. Better use -Og here.
    myenv['CXXFLAGS'] = str(myenv['CXXFLAGS']).replace('-O0', '-Og')
    myenv.Append(
        CXXFLAGS = ' -fno-exceptions -fno-rtti',
        LINKFLAGS = ' -fno-exceptions -fno-rtti -nostartfiles',
    )

    myenv.M3Program(
        myenv,
        target = 'rctmux',
        source = [
            env.Glob('arch/gem5-$ISA/*.S'),
            env.Glob('arch/gem5-$ISA/*.cc'),
            env.Glob('arch/' + env['ARCH'] + '/*.S'),
            env.Glob('arch/' + env['ARCH'] + '/*.cc'),
            env.Glob('*.cc'),
        ],
        NoSup = True,
        varAddr = False,
        ldscript = myenv.File('#src/apps/rctmux/arch/gem5/ld-${ISA}.conf'),
        libs = ['gcc', 'c', 'isr']
    )
