Import('env')

myenv = env.Clone()
myenv.Append(CXXFLAGS = ' -fno-exceptions')
myenv['CXXFLAGS'] = str(myenv['CXXFLAGS']).replace('-flto', '')
lib = myenv.StaticLibrary(
    target = 'libisr',
    source = [
        myenv.Glob('arch/$ISA/*.cc'),
        myenv.Glob('arch/$ISA/*.S'),
        myenv.Glob('*.cc'),
    ],
)
myenv.Install(myenv['LIBDIR'], lib)
