Import('env', 'hostenv')

for d in ['kernel', 'server', 'libs', 'apps', 'fs']:
    env.SConscript(d + '/SConscript', exports = ['env', 'hostenv'])
hostenv.SConscript('tools/SConscript', exports = 'hostenv')
