Import('env', 'hostenv')

if ARGUMENTS.get('build_fs', 0):
    env.SConscript('fs/SConscript', exports = ['env', 'hostenv'])
else:
    for d in ['kernel', 'server', 'libs', 'apps', 'fs']:
        env.SConscript(d + '/SConscript', exports = ['env', 'hostenv'])
    hostenv.SConscript('tools/SConscript', exports = 'hostenv')
