Import('hostenv')

# check for tud-otfconfig
def CheckOTFConfig(context):
    context.Message('Checking for tud-otfconfig...')
    result = context.TryAction('tud-otfconfig')[0]
    context.Result(result)
    return result

traceenv = hostenv.Clone()
conf = Configure(traceenv, custom_tests={'CheckOTFConfig': CheckOTFConfig})

if conf.CheckOTFConfig():
    traceenv.ParseConfig('tud-otfconfig --includes --libs')
    traceenv.Program(
        target = 'm3trace2otf',
        source = traceenv.Glob('*.cc'),
    )
else:
    print('Cannot execute tud-otfconfig, skipping m3trace2otf...')

conf.Finish()
