#
# Copyright (C) 2015, Nils Asmussen <nils@os.inf.tu-dresden.de>
# Economic rights: Technische Universitaet Dresden (Germany)
#
# This file is part of M3 (Microkernel-based SysteM for Heterogeneous Manycores).
#
# M3 is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# M3 is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License version 2 for more details.
#

#include <base/Asm.h>
#include <base/Config.h>

BEGIN_FUNC(_start)
    # stack pointer already set?
    li      t0, 0xDEADBEEF
    beq     t0, a0, 1f

    # set default stack pointer
    li      sp, (STACK_TOP - 4)

1:
    jal     env_run

    # just to be sure
1:  j       1b
END_FUNC(_start)

BEGIN_FUNC(_init)
    ret
END_FUNC(_init)
