import os

Import('env')

myenv = env.Clone()
myenv.Append(CXXFLAGS = ' -fno-exceptions')

sources = [
    myenv.Glob('*.cc'), myenv.Glob('*/*.cc'),
    myenv.Glob('arch/$PLATF/*.cc'),
    myenv.Glob('arch/$TGT/*.cc'),
]

lib = myenv.StaticLibrary(
    target = 'libbase',
    source = sources
)
myenv.Install(myenv['LIBDIR'], lib)
