import os

Import('env')

myenv = env.Clone()
myenv.Append(CXXFLAGS = ' -fno-exceptions')

sources = [
    myenv.Glob('*.cc'), myenv.Glob('*/*.cc'),
    myenv.Glob('arch/$ARCH-$ISA/*.S'), myenv.Glob('arch/$ARCH-$ISA/*.cc'),
    myenv.Glob('arch/$ARCH/*.S'), myenv.Glob('arch/$ARCH/*.cc'),
    myenv.Glob('arch/$ISA/*.S'), myenv.Glob('arch/$ISA/*.cc')
]
if myenv['ARCH'] != 'host':
    sources += [myenv.Glob('arch/baremetal/*.cc')]

lib = myenv.StaticLibrary(
    target = 'libbase',
    source = sources
)
myenv.Install(myenv['LIBDIR'], lib)
