import os

Import('env')

def BuildFSImage(env, target, source, blocks, inodes):
    def is_bin(f):
        if f.abspath.endswith('kernel'):
            return False
        if f.abspath.endswith('.a'):
            return False
        if f.abspath.endswith('.rlib'):
            return False
        return True

    for f in env.Glob('$BINARYDIR/*'):
        if is_bin(f):
            env.M3Strip(source + '/bin/${SOURCE.file}', f)

    env.M3Mkfs(target, source, blocks = blocks, inodes = inodes)

env = env.Clone()
env.AddMethod(BuildFSImage)
env.SConscript(Glob('*/SConscript'), 'env')
